# Generated by Django 2.2 on 2020-07-25 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200725_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpost',
            options={'ordering': ['-publish_date']},
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='updated',
        ),
    ]
